@JwtAuthApi_HostAddress = https://localhost:7164/api    

POST {{JwtAuthApi_HostAddress}}/update_role
Content-Type: application/json
Authorization: Bearer {{AuthToken}}
{
  "userId": 5,
  "newRole": "a.monzer"
}

###
