@JwtAuthApi_HostAddress = https://localhost:7164/auth

POST {{JwtAuthApi_HostAddress}}/login
Content-Type: application/json
#Authorization: Bearer 

{
    "Username": "teest",
    "Password": "1234"
}

###
